import AppKit
import Carbon
import Combine
import SwiftUI

@MainActor
final class VeeSettings: ObservableObject {
    @AppStorage("visibleItemCount") var visibleItemCount = 5 {
        willSet { objectWillChange.send() }
    }

    @AppStorage("hotKeyKeyCode") private var storedHotKeyKeyCode = Int(kVK_ANSI_V) {
        willSet { objectWillChange.send() }
    }

    @AppStorage("hotKeyModifiers") private var storedHotKeyModifiers = Int(cmdKey | optionKey) {
        willSet { objectWillChange.send() }
    }

    var hotKeyKeyCode: UInt32 {
        get { UInt32(storedHotKeyKeyCode) }
        set {
            objectWillChange.send()
            storedHotKeyKeyCode = Int(newValue)
        }
    }

    var hotKeyModifiers: UInt32 {
        get { UInt32(storedHotKeyModifiers) }
        set {
            objectWillChange.send()
            storedHotKeyModifiers = Int(newValue)
        }
    }
}

@MainActor
final class ClipboardStore: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let maxItems = 60
    private var suspendedUntil = Date.distantPast
    private var lastAddition: (content: String, previousTop: String?, wasFresh: Bool, at: Date)?

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.3, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.poll()
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Skip pasteboard changes for a while — used around Vee's own paste,
    /// which temporarily rewrites the pasteboard.
    func suspendCapture(for interval: TimeInterval) {
        suspendedUntil = Date().addingTimeInterval(interval)
    }

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else {
            return
        }

        lastChangeCount = pasteboard.changeCount

        guard Date() >= suspendedUntil else {
            return
        }

        guard !pasteboard.containsTransientContent,
              let string = pasteboard.string(forType: .string),
              !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return
        }

        // Dictation and snippet tools write their text, send Cmd-V, then put
        // the previous contents back. When the pasteboard reverts to the
        // pre-injection value right after a fresh addition, drop that entry.
        if let last = lastAddition,
           last.wasFresh,
           Date().timeIntervalSince(last.at) < 2.5,
           string == last.previousTop,
           items.first?.content == last.content {
            items.removeFirst()
            lastAddition = nil
            return
        }

        add(string)
    }

    private func add(_ string: String) {
        let previousTop = items.first?.content
        let wasFresh = !items.contains { $0.content == string }

        items.removeAll { $0.content == string }
        items.insert(ClipboardItem(content: string, copiedAt: Date()), at: 0)

        if items.count > maxItems {
            items.removeLast(items.count - maxItems)
        }

        lastAddition = (string, previousTop, wasFresh, Date())
    }
}

private extension NSPasteboard {
    /// Markers from nspasteboard.org: passwords, transient writes from
    /// paste/dictation tools, and other auto-generated content.
    var containsTransientContent: Bool {
        let markers = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType"
        ].map { NSPasteboard.PasteboardType($0) }

        if let types, markers.contains(where: types.contains) {
            return true
        }

        return pasteboardItems?.contains { item in
            markers.contains(where: item.types.contains)
        } == true
    }
}
